name: Terraform GitHub Actions Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
	  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
	  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
	  AWS_DEFAULT_REGION: 'ap-northeast-2'

    steps:
    # 저장소로 부터 코드를 내려받기 위한 체크아웃(Checkout) 액션
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false
